In [2]:
import pandas as pd
import numpy as np

In [3]:
#Create a DataFrame for the inbound trasactional feed
tradeDF=pd.read_csv('/home/cloudera/TRADE_TXN_FEED.csv')

In [4]:
##Sample the data to see if the file is read and the headers are lined correctly
tradeDF.head()

,trade_id,trade_name,trade_type,trade_dt,trade_settlement_dt,transaction_type,trade_quantity,branch_name,branch_location_id,lob,...,symbol_type,quantity,acct_num,acct_name,acct_type,acct_sub_type,product_id,product_name,product_desc,product_category
0,1000000.0,AT,AUTOMATIC TRADE,2018-01-31,2018-02-02,BUY,100.0,CHI,LOC001,UNKNOWN,...,SYMBOL-ABC_TYP,100,99997,ACCT001,Undeposited Funds,SUB_TYPE_AC,777777,MUNI,UNKNOWN,MUNI
1,1000001.0,OTC,OTC Trade,2018-02-01,2018-02-03,SELL,101.0,NYC,LOC002,UNKNOWN,...,SYMBOL-ABC_TYP,100,99998,ACCT002,Income Accounts,SUB_TYPE_AC,777778,CORP,UNKNOWN,CORP
2,1000002.0,ON,On- EXCHANGE,2018-02-02,2018-02-04,CANCEL,77.0,OHC,LOC003,UNKNOWN,...,SYMBOL-ABC_TYP,100,99999,ACCT001,Assets,SUB_TYPE_AC,777779,GOVT,UNKNOWN,GOVT
3,1000003.0,AT,AUTOMATIC TRADE,2018-02-03,2018-02-05,ADJUST,90.0,KNC,LOC004,UNKNOWN,...,SYMBOL-ABC_TYP,100,100000,ACCT002,Liabilities,SUB_TYPE_AC,777780,EQUITY,UNKNOWN,EQUITY
4,1000004.0,OTC,OTC Trade,2018-02-04,2018-02-06,BUY,65.0,LAL,LOC005,UNKNOWN,...,SYMBOL-ABC_TYP,100,100001,ACCT001,Undeposited Funds,SUB_TYPE_AC,777781,TEST,UNKNOWN,TEST

In [5]:
#Total Number of unique trade id (num of transactions in feed)
tradeDF.trade_id.count()

9096

In [6]:
#The verification of the file layout, to help make sure all the attributes needed are captured by the dataFrame
tradeDF.columns

Index([u'trade_id', u'trade_name', u'trade_type', u'trade_dt',
       u'trade_settlement_dt', u'transaction_type', u'trade_quantity',
       u'branch_name', u'branch_location_id', u'lob', u'org_unit', u'fa_num',
       u'fa_split', u'cusip', u'start_dt', u'end_dt', u'symbol',
       u'symbol_type', u'quantity', u'acct_num', u'acct_name', u'acct_type',
       u'acct_sub_type', u'product_id', u'product_name', u'product_desc',
       u'product_category'],
      dtype='object')

In [7]:
# All the datatypes of the inbound feed are described here
tradeDF.dtypes

trade_id               float64
trade_name              object
trade_type              object
trade_dt                object
trade_settlement_dt     object
transaction_type        object
trade_quantity         float64
branch_name             object
branch_location_id      object
lob                     object
org_unit                object
fa_num                  object
fa_split                object
cusip                   object
start_dt                object
end_dt                  object
symbol                  object
symbol_type             object
quantity                 int64
acct_num                 int64
acct_name               object
acct_type               object
acct_sub_type           object
product_id               int64
product_name            object
product_desc            object
product_category        object
dtype: object

In [8]:
#Filter Bad transactions with missing dates for trade_dt & trade_settlement dt
date_cleaned_tradeDF=tradeDF[tradeDF['trade_dt'].notnull() & tradeDF['trade_settlement_dt'].notnull()]

In [9]:
date_cleaned_tradeDF.count()

trade_id               8548
trade_name             8963
trade_type             8963
trade_dt               9159
trade_settlement_dt    9159
transaction_type       7328
trade_quantity         9159
branch_name            9159
branch_location_id     9159
lob                    9159
org_unit               9159
fa_num                 9159
fa_split               9159
cusip                  9159
start_dt               9159
end_dt                 9159
symbol                 9159
symbol_type            9159
quantity               9159
acct_num               9159
acct_name              9159
acct_type              9159
acct_sub_type          9159
product_id             9159
product_name           9159
product_desc           9159
product_category       9159
dtype: int64

In [10]:
# Drop rows that have too many null values in the record ( say 5 or more)
date_cleaned_tradeDF.dropna(thresh=5)

,trade_id,trade_name,trade_type,trade_dt,trade_settlement_dt,transaction_type,trade_quantity,branch_name,branch_location_id,lob,...,symbol_type,quantity,acct_num,acct_name,acct_type,acct_sub_type,product_id,product_name,product_desc,product_category
0,1000000.0,AT,AUTOMATIC TRADE,2018-01-31,2018-02-02,BUY,100.000000,CHI,LOC001,UNKNOWN,...,SYMBOL-ABC_TYP,100,99997,ACCT001,Undeposited Funds,SUB_TYPE_AC,777777,MUNI,UNKNOWN,MUNI
1,1000001.0,OTC,OTC Trade,2018-02-01,2018-02-03,SELL,101.000000,NYC,LOC002,UNKNOWN,...,SYMBOL-ABC_TYP,100,99998,ACCT002,Income Accounts,SUB_TYPE_AC,777778,CORP,UNKNOWN,CORP
2,1000002.0,ON,On- EXCHANGE,2018-02-02,2018-02-04,CANCEL,77.000000,OHC,LOC003,UNKNOWN,...,SYMBOL-ABC_TYP,100,99999,ACCT001,Assets,SUB_TYPE_AC,777779,GOVT,UNKNOWN,GOVT
3,1000003.0,AT,AUTOMATIC TRADE,2018-02-03,2018-02-05,ADJUST,90.000000,KNC,LOC004,UNKNOWN,...,SYMBOL-ABC_TYP,100,100000,ACCT002,Liabilities,SUB_TYPE_AC,777780,EQUITY,UNKNOWN,EQUITY
4,1000004.0,OTC,OTC Trade,2018-02-04,2018-02-06,BUY,65.000000,LAL,LOC005,UNKNOWN,...,SYMBOL-ABC_TYP,100,100001,ACCT001,Undeposited Funds,SUB_TYPE_AC,777781,TEST,UNKNOWN,TEST
5,1000005.0,ON,On- EXCHANGE,2017-02-05,2017-02-07,BUY,43.000000,WYM,LOC006,UNKNOWN,...,SYMBOL-ABC_TYP,100,100002,ACCT002,Income Accounts,SUB_TYPE_AC,777782,DUMMY,UNKNOWN,DUMMY
6,1000006.0,AT,AUTOMATIC TRADE,2017-02-06,2017-02-08,SELL,41.333333,CHI,LOC007,UNKNOWN,...,SYMBOL-ABC_TYP,100,100003,ACCT001,Undeposited Funds,SUB_TYPE_AC,777783,MUNI,UNKNOWN,MUNI
7,1000007.0,OTC,OTC Trade,2017-02-07,2017-02-09,CANCEL,30.476190,NYC,LOC008,UNKNOWN,...,SYMBOL-ABC_TYP,100,100004,ACCT002,Income Accounts,SUB_TYPE_AC,777784,CORP,UNKNOWN,CORP
8,1000008.0,ON,On- EXCHANGE,2017-02-08,2017-02-10,ADJUST,19.619048,OHC,LOC009,UNKNOWN,...,SYMBOL-ABC_TYP,100,100005,ACCT001,Assets,SUB_TYPE_AC,777785,GOVT,UNKNOWN,GOVT
9,1000009.0,AT,AUTOMATIC TRADE,2017-02-09,2017-02-11,NaN,8.761905,KNC,LOC010,UNKNOWN,...,SYMBOL-ABC_TYP,100,100006,ACCT002,Liabilities,SUB_TYPE_AC,777786,EQUITY,UNKNOWN,EQUITY
10,1000010.0,OTC,OTC Trade,2017-02-10,2017-02-12,BUY,-2.095238,LAL,LOC011,UNKNOWN,...,SYMBOL-ABC_TYP,100,100007,ACCT001,Undeposited Funds,SUB_TYPE_AC,777787,TEST,UNKNOWN,TEST
11,1000011.0,ON,On- EXCHANGE,2017-02-11,2017-02-13,SELL,-12.952381,WYM,LOC012,UNKNOWN,...,SYMBOL-ABC_TYP,100,100008,ACCT002,Income Accounts,SUB_TYPE_AC,777788,DUMMY,UNKNOWN,DUMMY
12,1000012.0,AT,AUTOMATIC TRADE,2017-02-12,2017-02-14,CANCEL,-23.809524,CHI,LOC013,UNKNOWN,...,SYMBOL-ABC_TYP,100,100009,ACCT001,Undeposited Funds,SUB_TYPE_AC,777789,MUNI,UNKNOWN,MUNI
13,1000013.0,OTC,OTC Trade,2017-02-13,2017-02-15,ADJUST,-34.666667,NYC,LOC014,UNKNOWN,...,SYMBOL-ABC_TYP,100,100010,ACCT002,Income Accounts,SUB_TYPE_AC,777790,CORP,UNKNOWN,CORP
14,1000014.0,ON,On- EXCHANGE,2017-02-14,2017-02-16,NaN,-45.523810,OHC,LOC015,UNKNOWN,...,SYMBOL-ABC_TYP,100,100011,ACCT001,Assets,SUB_TYPE_AC,777791,GOVT,UNKNOWN,GOVT
15,1000015.0,AT,AUTOMATIC TRADE,2017-02-15,2017-02-17,BUY,-56.380952,KNC,LOC016,UNKNOWN,...,SYMBOL-ABC_TYP,100,100012,ACCT002,Liabilities,SUB_TYPE_AC,777792,EQUITY,UNKNOWN,EQUITY
16,1000016.0,OTC,OTC Trade,2017-02-16,2017-02-18,SELL,-67.238095,LAL,LOC017,UNKNOWN,...,SYMBOL-ABC_TYP,100,100013,ACCT001,Undeposited Funds,SUB_TYPE_AC,777793,TEST,UNKNOWN,TEST
17,1000017.0,ON,On- EXCHANGE,2017-02-17,2017-02-19,CANCEL,-78.095238,WYM,LOC018,UNKNOWN,...,SYMBOL-ABC_TYP,100,100014,ACCT002,Income Accounts,SUB_TYPE_AC,777794,DUMMY,UNKNOWN,DUMMY
18,1000018.0,AT,AUTOMATIC TRADE,2017-02-18,2017-02-20,ADJUST,-88.952381,CHI,LOC019,UNKNOWN,...,SYMBOL-ABC_TYP,100,100015,ACCT001,Undeposited Funds,SUB_TYPE_AC,777795,MUNI,UNKNOWN,MUNI
19,1000019.0,OTC,OTC Trade,2017-02-19,2017-02-21,NaN,-99.809524,NYC,LOC020,UNKNOWN,...,SYMBOL-ABC_TYP,100,100016,ACCT002,Income Accounts,SUB_TYPE_AC,777796,CORP,UNKNOWN,CORP
20,1000020.0,ON,On- EXCHANGE,2017-02-20,2017-02-22,BUY,-110.666667,OHC,LOC021,UNKNOWN,...,SYMBOL-ABC_TYP,100,100017,ACCT001,Assets,SUB_TYPE_AC,777797,GOVT,UNKNOWN,GOVT
21,1000021.0,AT,AUTOMATIC TRADE,2017-02-21,2017-02-23,SELL,-121.523809,KNC,LOC022,UNKNOWN,...,SYMBOL-ABC_TYP,100,100018,ACCT002,Liabilities,SUB_TYPE_AC,777798,EQUITY,UNKNOWN,EQUITY
22,1000022.0,OTC,OTC Trade,2017-02-22,2017-02-24,CANCEL,-132.380952,LAL,LOC023,UNKNOWN,...,SYMBOL-ABC_TYP,100,100019,ACCT001,Undeposited Funds,SUB_TYPE_AC,777799,TEST,UNKNOWN,TEST
23,1000023.0,ON,On- EXCHANGE,2017-02-23,2017-02-25,ADJUST,-143.238095,WYM,LOC024,UNKNOWN,...,SYMBOL-ABC_TYP,100,100020,ACCT002,Income Accounts,SUB_TYPE_AC,777800,DUMMY,UNKNOWN,DUMMY
24,1000024.0,AT,AUTOMATIC TRADE,2017-02-24,2017-02-26,NaN,-154.095238,CHI,LOC025,UNKNOWN,...,SYMBOL-ABC_TYP,100,100021,ACCT001,Undeposited Funds,SUB_TYPE_AC,777801,MUNI,UNKNOWN,MUNI
25,1000025.0,OTC,OTC Trade,2017-02-25,2017-02-27,BUY,-164.952381,NYC,LOC026,UNKNOWN,...,SYMBOL-ABC_TYP,100,100022,ACCT002,Income Accounts,SUB_TYPE_AC,777802,CORP,UNKNOWN,CORP
26,1000026.0,ON,On- EXCHANGE,2017-02-26,2017-02-28,SELL,-175.809524,OHC,LOC027,UNKNOWN,...,SYMBOL-ABC_TYP,100,100023,ACCT001,Assets,SUB_TYPE_AC,777803,GOVT,UNKNOWN,GOVT
27,1000027.0,AT,AUTOMATIC TRADE,2017-02-27,2017-03-01,CANCEL,-186.666667,KNC,LOC028,UNKNOWN,...,SYMBOL-ABC_TYP,100,100024,ACCT002,Liabilities,SUB_TYPE_AC,777804,EQUITY,UNKNOWN,EQUITY
28,1000028.0,OTC,OTC Trade,2017-02-28,2017-03-02,ADJUST,-197.523809,LAL,LOC029,UNKNOWN,...,SYMBOL-ABC_TYP,100,100025,ACCT001,Undeposited Funds,SUB_TYPE_AC,777805,TEST,UNKNOWN,TEST
29,1000029.0,ON,On- EXCHANGE,2017-03-01,2017-03-03,NaN,-208.380952,WYM,LOC030,UNKNOWN,...,SYMBOL-ABC_TYP,100,100026,ACCT002,Income Accounts,SUB_TYPE_AC,777806,DUMMY,UNKNOWN,DUMMY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9677,NaN,NaN,NaN,2018-01-15,2018-01-17,CANCEL,-104958.095200,WYM,LOC9678,UNKNOWN,...,SYMBOL-ABC_TYP,100,109674,ACCT002,Income Accounts,SUB_TYPE_AC,787454,DUMMY,UNKNOWN,DUMMY
9678,NaN,NaN,NaN,2018-01-16,2018-01-18,ADJUST,-104968.952400,CHI,LOC9679,UNKNOWN,...,SYMBOL-ABC_TYP,100,109675,ACCT001,Undeposited Funds,SUB_TYPE_AC,787455,MUNI,UNKNOWN,MUNI
9679,NaN,NaN,NaN,2018-01-17,2018-01-19,NaN,-104979.809500,NYC,LOC9680,UNKNOWN,...,SYMBOL-ABC_TYP,100,109676,ACCT002,Income Accounts,SUB_TYPE_AC,787456,CORP,UNKNOWN,CORP
9680,NaN,NaN,NaN,2018-01-18,2018-01-20,BUY,-104990.666700,OHC,LOC9681,UNKNOWN,...,SYMBOL-ABC_TYP,100,109677,ACCT001,Assets,SUB_TYPE_AC,787457,GOVT,UNKNOWN,GOVT
9681,NaN,NaN,NaN,2018-01-19,2018-01-21,SELL,-105001.523800,KNC,LOC9682,UNKNOWN,...,SYMBOL-ABC_TYP,100,109678,ACCT002,Liabilities,SUB_TYPE_AC,787458,EQUITY,UNKNOWN,EQUITY
9682,NaN,NaN,NaN,2018-01-20,2018-01-22,CANCEL,-105012.381000,LAL,LOC9683,UNKNOWN,...,SYMBOL-ABC_TYP,100,109679,ACCT001,Undeposited Funds,SUB_TYPE_AC,787459,TEST,UNKNOWN,TEST
9683,NaN,NaN,NaN,2018-01-21,2018-01-23,ADJUST,-105023.238100,WYM,LOC9684,UNKNOWN,...,SYMBOL-ABC_TYP,100,109680,ACCT002,Income Accounts,SUB_TYPE_AC,787460,DUMMY,UNKNOWN,DUMMY
9684,NaN,NaN,NaN,2018-01-22,2018-01-24,NaN,-105034.095200,CHI,LOC9685,UNKNOWN,...,SYMBOL-ABC_TYP,100,109681,ACCT001,Undeposited Funds,SUB_TYPE_AC,787461,MUNI,UNKNOWN,MUNI
9685,NaN,NaN,NaN,2018-01-23,2018-01-25,BUY,-105044.952400,NYC,LOC9686,UNKNOWN,...,SYMBOL-ABC_TYP,100,109682,ACCT002,Income Accounts,SUB_TYPE_AC,787462,CORP,UNKNOWN,CORP
9686,NaN,NaN,NaN,2018-01-24,2018-01-26,SELL,-105055.809500,OHC,LOC9687,UNKNOWN,...,SYMBOL-ABC_TYP,100,109683,ACCT001,Assets,SUB_TYPE_AC,787463,GOVT,UNKNOWN,GOVT
9687,NaN,NaN,NaN,2018-01-25,2018-01-27,CANCEL,-105066.666700,KNC,LOC9688,UNKNOWN,...,SYMBOL-ABC_TYP,100,109684,ACCT002,Liabilities,SUB_TYPE_AC,787464,EQUITY,UNKNOWN,EQUITY
9688,NaN,NaN,NaN,2018-01-26,2018-01-28,ADJUST,-105077.523800,LAL,LOC9689,UNKNOWN,...,SYMBOL-ABC_TYP,100,109685,ACCT001,Undeposited Funds,SUB_TYPE_AC,787465,TEST,UNKNOWN,TEST
9689,NaN,NaN,NaN,2018-01-27,2018-01-29,NaN,-105088.381000,WYM,LOC9690,UNKNOWN,...,SYMBOL-ABC_TYP,100,109686,ACCT002,Income Accounts,SUB_TYPE_AC,787466,DUMMY,UNKNOWN,DUMMY
9690,NaN,NaN,NaN,2018-01-28,2018-01-30,BUY,-105099.238100,CHI,LOC9691,UNKNOWN,...,SYMBOL-ABC_TYP,100,109687,ACCT001,Undeposited Funds,SUB_TYPE_AC,787467,MUNI,UNKNOWN,MUNI
9691,NaN,NaN,NaN,2018-01-29,2018-01-31,SELL,-105110.095200,NYC,LOC9692,UNKNOWN,...,SYMBOL-ABC_TYP,100,109688,ACCT002,Income Accounts,SUB_TYPE_AC,787468,CORP,UNKNOWN,CORP
9692,NaN,NaN,NaN,2018-01-30,2018-02-01,CANCEL,-105120.952400,OHC,LOC9693,UNKNOWN,...,SYMBOL-ABC_TYP,100,109689,ACCT001,Assets,SUB_TYPE_AC,787469,GOVT,UNKNOWN,GOVT
9693,NaN,NaN,NaN,2018-01-31,2018-02-02,ADJUST,-105131.809500,KNC,LOC9694,UNKNOWN,...,SYMBOL-ABC_TYP,100,109690,ACCT002,Liabilities,SUB_TYPE_AC,787470,EQUITY,UNKNOWN,EQUITY
9694,NaN,NaN,NaN,2018-02-01,2018-02-03,NaN,-105142.666700,LAL,LOC9695,UNKNOWN,...,SYMBOL-ABC_TYP,100,109691,ACCT001,Undeposited Funds,SUB_TYPE_AC,787471,TEST,UNKNOWN,TEST
9695,NaN,NaN,NaN,2018-02-02,2018-02-04,BUY,-105153.523800,WYM,LOC9696,UNKNOWN,...,SYMBOL-ABC_TYP,100,109692,ACCT002,Income Accounts,SUB_TYPE_AC,787472,DUMMY,UNKNOWN,DUMMY
9696,NaN,NaN,NaN,2018-02-03,2018-02-05,SELL,-105164.381000,CHI,LOC9697,UNKNOWN,...,SYMBOL-ABC_TYP,100,109693,ACCT001,Undeposited Funds,SUB_TYPE_AC,787473,MUNI,UNKNOWN,MUNI
9697,NaN,NaN,NaN,2018-02-04,2018-02-06,CANCEL,-105175.238100,NYC,LOC9698,UNKNOWN,...,SYMBOL-ABC_TYP,100,109694,ACCT002,Income Accounts,SUB_TYPE_AC,787474,CORP,UNKNOWN,CORP
9698,NaN,NaN,NaN,2018-02-05,2018-02-07,ADJUST,-105186.095200,OHC,LOC9699,UNKNOWN,...,SYMBOL-ABC_TYP,100,109695,ACCT001,Assets,SUB_TYPE_AC,787475,GOVT,UNKNOWN,GOVT
9699,NaN,NaN,NaN,2018-02-06,2018-02-08,NaN,-105196.952400,KNC,LOC9700,UNKNOWN,...,SYMBOL-ABC_TYP,100,109696,ACCT002,Liabilities,SUB_TYPE_AC,787476,EQUITY,UNKNOWN,EQUITY
9700,NaN,NaN,NaN,2018-02-07,2018-02-09,BUY,-105207.809500,LAL,LOC9701,UNKNOWN,...,SYMBOL-ABC_TYP,100,109697,ACCT001,Undeposited Funds,SUB_TYPE_AC,787477,TEST,UNKNOWN,TEST
9701,NaN,NaN,NaN,2018-02-08,2018-02-10,SELL,-105218.666700,WYM,LOC9702,UNKNOWN,...,SYMBOL-ABC_TYP,100,109698,ACCT002,Income Accounts,SUB_TYPE_AC,787478,DUMMY,UNKNOWN,DUMMY
9702,NaN,NaN,NaN,2018-02-09,2018-02-11,CANCEL,-105229.523800,CHI,LOC9703,UNKNOWN,...,SYMBOL-ABC_TYP,100,109699,ACCT001,Undeposited Funds,SUB_TYPE_AC,787479,MUNI,UNKNOWN,MUNI
9703,NaN,NaN,NaN,2018-02-10,2018-02-12,ADJUST,-105240.381000,NYC,LOC9704,UNKNOWN,...,SYMBOL-ABC_TYP,100,109700,ACCT002,Income Accounts,SUB_TYPE_AC,787480,CORP,UNKNOWN,CORP
9704,NaN,NaN,NaN,2018-02-11,2018-02-13,NaN,-105251.238100,OHC,LOC9705,UNKNOWN,...,SYMBOL-ABC_TYP,100,109701,ACCT001,Assets,SUB_TYPE_AC,787481,GOVT,UNKNOWN,GOVT
9705,NaN,NaN,NaN,2018-02-12,2018-02-14,BUY,-105262.095200,KNC,LOC9706,UNKNOWN,...,SYMBOL-ABC_TYP,100,109702,ACCT002,Liabilities,SUB_TYPE_AC,787482,EQUITY,UNKNOWN,EQUITY
9706,NaN,NaN,NaN,2018-02-13,2018-02-15,SELL,-105272.952400,LAL,LOC9707,UNKNOWN,...,SYMBOL-ABC_TYP,100,109703,ACCT001,Undeposited Funds,SUB_TYPE_AC,787483,TEST,UNKNOWN,TEST

In [11]:
date_cleaned_tradeDF.count()

trade_id               8548
trade_name             8963
trade_type             8963
trade_dt               9159
trade_settlement_dt    9159
transaction_type       7328
trade_quantity         9159
branch_name            9159
branch_location_id     9159
lob                    9159
org_unit               9159
fa_num                 9159
fa_split               9159
cusip                  9159
start_dt               9159
end_dt                 9159
symbol                 9159
symbol_type            9159
quantity               9159
acct_num               9159
acct_name              9159
acct_type              9159
acct_sub_type          9159
product_id             9159
product_name           9159
product_desc           9159
product_category       9159
dtype: int64

In [12]:
#Selectively pick only BUY/SELL/ADJUST and filterout cancelled trades
# IN CLAUSE WAS POSING ISSUE 
date_cleaned_tradeDF=date_cleaned_tradeDF[date_cleaned_tradeDF['transaction_type'].isin(['BUY','SELL','ADJUST']) ]

In [13]:
#Look at the counts and shape of the frame, it is now rid of a lot of cancled data
date_cleaned_tradeDF.count()

trade_id               5130
trade_name             5379
trade_type             5379
trade_dt               5497
trade_settlement_dt    5497
transaction_type       5497
trade_quantity         5497
branch_name            5497
branch_location_id     5497
lob                    5497
org_unit               5497
fa_num                 5497
fa_split               5497
cusip                  5497
start_dt               5497
end_dt                 5497
symbol                 5497
symbol_type            5497
quantity               5497
acct_num               5497
acct_name              5497
acct_type              5497
acct_sub_type          5497
product_id             5497
product_name           5497
product_desc           5497
product_category       5497
dtype: int64

In [14]:
#Sometimes the trade quantity may come in as null,
#one way to handle is to drop but another bussiness case is to apply a mean of the existing data
mean_quantity=date_cleaned_tradeDF['trade_quantity'].mean(axis=0)
date_cleaned_tradeDF.replace(np.nan,mean_quantity,inplace=True)

In [15]:
# We noticed some negative numbers on the file, this will ensure that is taken care of 
date_cleaned_tradeDF['trade_quantity']=date_cleaned_tradeDF['trade_quantity'].abs()

In [16]:
date_cleaned_tradeDF.tail()

,trade_id,trade_name,trade_type,trade_dt,trade_settlement_dt,transaction_type,trade_quantity,branch_name,branch_location_id,lob,...,symbol_type,quantity,acct_num,acct_name,acct_type,acct_sub_type,product_id,product_name,product_desc,product_category
9700,-51461.996215,-51462,-51462,2018-02-07,2018-02-09,BUY,105207.8095,LAL,LOC9701,UNKNOWN,...,SYMBOL-ABC_TYP,100,109697,ACCT001,Undeposited Funds,SUB_TYPE_AC,787477,TEST,UNKNOWN,TEST
9701,-51461.996215,-51462,-51462,2018-02-08,2018-02-10,SELL,105218.6667,WYM,LOC9702,UNKNOWN,...,SYMBOL-ABC_TYP,100,109698,ACCT002,Income Accounts,SUB_TYPE_AC,787478,DUMMY,UNKNOWN,DUMMY
9703,-51461.996215,-51462,-51462,2018-02-10,2018-02-12,ADJUST,105240.3810,NYC,LOC9704,UNKNOWN,...,SYMBOL-ABC_TYP,100,109700,ACCT002,Income Accounts,SUB_TYPE_AC,787480,CORP,UNKNOWN,CORP
9705,-51461.996215,-51462,-51462,2018-02-12,2018-02-14,BUY,105262.0952,KNC,LOC9706,UNKNOWN,...,SYMBOL-ABC_TYP,100,109702,ACCT002,Liabilities,SUB_TYPE_AC,787482,EQUITY,UNKNOWN,EQUITY
9706,-51461.996215,-51462,-51462,2018-02-13,2018-02-15,SELL,105272.9524,LAL,LOC9707,UNKNOWN,...,SYMBOL-ABC_TYP,100,109703,ACCT001,Undeposited Funds,SUB_TYPE_AC,787483,TEST,UNKNOWN,TEST

In [17]:
# This will give us the number of rows(indexs) and columns(attributes)
date_cleaned_tradeDF.shape

(5497, 27)

In [18]:
date_cleaned_tradeDF.index

Int64Index([   0,    1,    3,    4,    5,    6,    8,   10,   11,   13,
            ...
            9691, 9693, 9695, 9696, 9698, 9700, 9701, 9703, 9705, 9706],
           dtype='int64', length=5497)

In [19]:
#Index list of attributes
date_cleaned_tradeDF.columns

Index([u'trade_id', u'trade_name', u'trade_type', u'trade_dt',
       u'trade_settlement_dt', u'transaction_type', u'trade_quantity',
       u'branch_name', u'branch_location_id', u'lob', u'org_unit', u'fa_num',
       u'fa_split', u'cusip', u'start_dt', u'end_dt', u'symbol',
       u'symbol_type', u'quantity', u'acct_num', u'acct_name', u'acct_type',
       u'acct_sub_type', u'product_id', u'product_name', u'product_desc',
       u'product_category'],
      dtype='object')

In [20]:
date_cleaned_tradeDF.describe(include='all')

,trade_id,trade_name,trade_type,trade_dt,trade_settlement_dt,transaction_type,trade_quantity,branch_name,branch_location_id,lob,...,symbol_type,quantity,acct_num,acct_name,acct_type,acct_sub_type,product_id,product_name,product_desc,product_category
count,5.497000e+03,5497,5497,5497,5497,5497,5497.000000,5497,5497,5497,...,5497,5497.0,5497.000000,5497,5497,5497,5497.000000,5497,5497,5497
unique,NaN,4,4,374,374,3,NaN,6,5497,1,...,1,NaN,NaN,2,4,1,NaN,6,1,6
top,NaN,OTC,AUTOMATIC TRADE,2018-02-01,2018-02-03,BUY,NaN,KNC,LOC7856,UNKNOWN,...,SYMBOL-ABC_TYP,NaN,NaN,ACCT002,Income Accounts,SUB_TYPE_AC,NaN,EQUITY,UNKNOWN,EQUITY
freq,NaN,1794,1794,31,31,1834,NaN,917,1,5497,...,5497,NaN,NaN,2750,1833,5497,NaN,917,5497,917
mean,9.339226e+05,NaN,NaN,NaN,NaN,NaN,51462.163562,NaN,NaN,NaN,...,NaN,100.0,104746.727852,NaN,NaN,NaN,782526.727852,NaN,NaN,NaN
std,2.635965e+05,NaN,NaN,NaN,NaN,NaN,30622.270812,NaN,NaN,NaN,...,NaN,0.0,2820.498000,NaN,NaN,NaN,2820.498000,NaN,NaN,NaN
min,-5.146200e+04,NaN,NaN,NaN,NaN,NaN,2.095238,NaN,NaN,NaN,...,NaN,100.0,99997.000000,NaN,NaN,NaN,777777.000000,NaN,NaN,NaN
25%,1.001676e+06,NaN,NaN,NaN,NaN,NaN,24734.666670,NaN,NaN,NaN,...,NaN,100.0,102285.000000,NaN,NaN,NaN,780065.000000,NaN,NaN,NaN
50%,1.003966e+06,NaN,NaN,NaN,NaN,NaN,49597.523810,NaN,NaN,NaN,...,NaN,100.0,104575.000000,NaN,NaN,NaN,782355.000000,NaN,NaN,NaN
75%,1.006516e+06,NaN,NaN,NaN,NaN,NaN,77283.238100,NaN,NaN,NaN,...,NaN,100.0,107125.000000,NaN,NaN,NaN,784905.000000,NaN,NaN,NaN
max,1.009095e+06,NaN,NaN,NaN,NaN,NaN,105272.952400,NaN,NaN,NaN,...,NaN,100.0,109703.000000,NaN,NaN,NaN,787483.000000,NaN,NaN,NaN

In [13]:
# Once cleaned please move to file to /tmp/venkat/clean/

import os
os.system("hadoop fs -mkdir -p /tmp/venkat/clean")
os.system("hadoop fs -put /home/cloudera/trade_feed_clean.csv /tmp/venkat/clean/")

0

In [14]:
from pyspark.sql import HiveContext
ss = HiveContext(sc)
ss.sql('show tables').head(1000)
#Create a Database for the used case
ss.sql('create database if not exists usedcase')
# Create Landing table if it does not exist

DataFrame[result: string]

In [7]:
ss.sql('show tables').head(1000)

[Row(tableName=u'abbb', isTemporary=False),
 Row(tableName=u'dim_acct', isTemporary=False),
 Row(tableName=u'dim_acct_delta', isTemporary=False),
 Row(tableName=u'dim_acct_ext', isTemporary=False),
 Row(tableName=u'dim_branch', isTemporary=False),
 Row(tableName=u'dim_branch_delta', isTemporary=False),
 Row(tableName=u'dim_branch_ext', isTemporary=False),
 Row(tableName=u'dim_product', isTemporary=False),
 Row(tableName=u'dim_product_delta', isTemporary=False),
 Row(tableName=u'dim_product_ext', isTemporary=False),
 Row(tableName=u'dim_security', isTemporary=False),
 Row(tableName=u'dim_security_delta', isTemporary=False),
 Row(tableName=u'dim_security_ext', isTemporary=False),
 Row(tableName=u'dim_trade', isTemporary=False),
 Row(tableName=u'dim_trade_delta', isTemporary=False),
 Row(tableName=u'dim_trade_ext', isTemporary=False),
 Row(tableName=u'fact_trade_txn_details', isTemporary=False),
 Row(tableName=u'land_trade_feed', isTemporary=False),
 Row(tableName=u'web_logs', isTemporary=False)]

In [15]:
# Create Landing table if it does not exist
ss.sql('create table if not exists usedcase.land_trade_feed(rec_id int, trade_id int, trade_name string, trade_type string,trade_dt string,trade_settlement_dt string,transaction_type string,trade_quantity int,branch_name string,branch_location_id string,lob string,org_unit string,fa_num string,fa_split string,cusip string,start_dt string,end_dt string,symbols string,symbol_type string,quantity string,acct_num string,acct_name string,acct_type string,acct_sub_type string,product_id int,product_name string,product_desc string,product_category string) row format delimited fields terminated by "," stored as textfile')

DataFrame[result: string]

In [16]:
#Load data Into the landing table, It can be the full file on day one or delta on subsequent days 
ss.sql("load data inpath '/tmp/venkat/clean/trade_feed_clean.csv' overwrite into table usedcase.land_trade_feed")

DataFrame[result: string]

In [17]:
for rec in ss.sql('select *  from usedcase.land_trade_feed').head(10):
    print rec

Row(rec_id=None, trade_id=None, trade_name=u'trade_name', trade_type=u'trade_type', trade_dt=u'trade_dt', trade_settlement_dt=u'trade_settlement_dt', transaction_type=u'transaction_type', trade_quantity=None, branch_name=u'branch_name', branch_location_id=u'branch_location_id', lob=u'lob', org_unit=u'org_unit', fa_num=u'fa_num', fa_split=u'fa_split', cusip=u'cusip', start_dt=u'start_dt', end_dt=u'end_dt', symbols=u'symbol', symbol_type=u'symbol_type', quantity=u'quantity', acct_num=u'acct_num', acct_name=u'acct_name', acct_type=u'acct_type', acct_sub_type=u'acct_sub_type', product_id=None, product_name=u'product_name', product_desc=u'product_desc', product_category=u'product_category')
Row(rec_id=0, trade_id=1000000, trade_name=u'AT', trade_type=u'AUTOMATIC TRADE', trade_dt=u'2018-01-31', trade_settlement_dt=u'2018-02-02', transaction_type=u'BUY', trade_quantity=100, branch_name=u'CHI', branch_location_id=u'LOC001', lob=u'UNKNOWN', org_unit=u'ORG1', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112345', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'99997', acct_name=u'ACCT001', acct_type=u'Undeposited Funds', acct_sub_type=u'SUB_TYPE_AC', product_id=777777, product_name=u'MUNI', product_desc=u'UNKNOWN', product_category=u'MUNI')
Row(rec_id=1, trade_id=1000001, trade_name=u'OTC', trade_type=u'OTC Trade', trade_dt=u'2018-02-01', trade_settlement_dt=u'2018-02-03', transaction_type=u'SELL', trade_quantity=101, branch_name=u'NYC', branch_location_id=u'LOC002', lob=u'UNKNOWN', org_unit=u'ORG2', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112346', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'99998', acct_name=u'ACCT002', acct_type=u'Income Accounts', acct_sub_type=u'SUB_TYPE_AC', product_id=777778, product_name=u'CORP', product_desc=u'UNKNOWN', product_category=u'CORP')
Row(rec_id=3, trade_id=1000003, trade_name=u'AT', trade_type=u'AUTOMATIC TRADE', trade_dt=u'2018-02-03', trade_settlement_dt=u'2018-02-05', transaction_type=u'ADJUST', trade_quantity=90, branch_name=u'KNC', branch_location_id=u'LOC004', lob=u'UNKNOWN', org_unit=u'ORG4', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112348', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100000', acct_name=u'ACCT002', acct_type=u'Liabilities', acct_sub_type=u'SUB_TYPE_AC', product_id=777780, product_name=u'EQUITY', product_desc=u'UNKNOWN', product_category=u'EQUITY')
Row(rec_id=4, trade_id=1000004, trade_name=u'OTC', trade_type=u'OTC Trade', trade_dt=u'2018-02-04', trade_settlement_dt=u'2018-02-06', transaction_type=u'BUY', trade_quantity=65, branch_name=u'LAL', branch_location_id=u'LOC005', lob=u'UNKNOWN', org_unit=u'ORG5', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112349', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100001', acct_name=u'ACCT001', acct_type=u'Undeposited Funds', acct_sub_type=u'SUB_TYPE_AC', product_id=777781, product_name=u'TEST', product_desc=u'UNKNOWN', product_category=u'TEST')
Row(rec_id=5, trade_id=1000005, trade_name=u'ON', trade_type=u'On- EXCHANGE', trade_dt=u'2017-02-05', trade_settlement_dt=u'2017-02-07', transaction_type=u'BUY', trade_quantity=43, branch_name=u'WYM', branch_location_id=u'LOC006', lob=u'UNKNOWN', org_unit=u'ORG6', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112350', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100002', acct_name=u'ACCT002', acct_type=u'Income Accounts', acct_sub_type=u'SUB_TYPE_AC', product_id=777782, product_name=u'DUMMY', product_desc=u'UNKNOWN', product_category=u'DUMMY')
Row(rec_id=6, trade_id=1000006, trade_name=u'AT', trade_type=u'AUTOMATIC TRADE', trade_dt=u'2017-02-06', trade_settlement_dt=u'2017-02-08', transaction_type=u'SELL', trade_quantity=41, branch_name=u'CHI', branch_location_id=u'LOC007', lob=u'UNKNOWN', org_unit=u'ORG7', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112351', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100003', acct_name=u'ACCT001', acct_type=u'Undeposited Funds', acct_sub_type=u'SUB_TYPE_AC', product_id=777783, product_name=u'MUNI', product_desc=u'UNKNOWN', product_category=u'MUNI')
Row(rec_id=8, trade_id=1000008, trade_name=u'ON', trade_type=u'On- EXCHANGE', trade_dt=u'2017-02-08', trade_settlement_dt=u'2017-02-10', transaction_type=u'ADJUST', trade_quantity=19, branch_name=u'OHC', branch_location_id=u'LOC009', lob=u'UNKNOWN', org_unit=u'ORG9', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112353', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100005', acct_name=u'ACCT001', acct_type=u'Assets', acct_sub_type=u'SUB_TYPE_AC', product_id=777785, product_name=u'GOVT', product_desc=u'UNKNOWN', product_category=u'GOVT')
Row(rec_id=10, trade_id=1000010, trade_name=u'OTC', trade_type=u'OTC Trade', trade_dt=u'2017-02-10', trade_settlement_dt=u'2017-02-12', transaction_type=u'BUY', trade_quantity=2, branch_name=u'LAL', branch_location_id=u'LOC011', lob=u'UNKNOWN', org_unit=u'ORG11', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112355', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100007', acct_name=u'ACCT001', acct_type=u'Undeposited Funds', acct_sub_type=u'SUB_TYPE_AC', product_id=777787, product_name=u'TEST', product_desc=u'UNKNOWN', product_category=u'TEST')
Row(rec_id=11, trade_id=1000011, trade_name=u'ON', trade_type=u'On- EXCHANGE', trade_dt=u'2017-02-11', trade_settlement_dt=u'2017-02-13', transaction_type=u'SELL', trade_quantity=12, branch_name=u'WYM', branch_location_id=u'LOC012', lob=u'UNKNOWN', org_unit=u'ORG12', fa_num=u'ABC', fa_split=u'XYZ', cusip=u'C00112356', start_dt=u'2017-01-31', end_dt=u'2017-12-31', symbols=u'SYMBOL-ABC', symbol_type=u'SYMBOL-ABC_TYP', quantity=u'100', acct_num=u'100008', acct_name=u'ACCT002', acct_type=u'Income Accounts', acct_sub_type=u'SUB_TYPE_AC', product_id=777788, product_name=u'DUMMY', product_desc=u'UNKNOWN', product_category=u'DUMMY')

In [18]:
#Creating product dim. external textfile storage table
ss.sql('create external table if not exists usedcase.dim_product_ext(product_id int,product_name string,product_desc string,product_category string)  stored as textfile')

DataFrame[result: string]

In [19]:
#Creating account dim. external textfile storage table
ss.sql('create external table if not exists usedcase.dim_acct_ext(acct_num int,acct_name string,acct_type string,acct_sub_type string)  stored as textfile')

DataFrame[result: string]

In [20]:
#Creating branch dim. external textfile storage table
ss.sql('create external table if not exists usedcase.dim_branch_ext(branch_id int,branch_name string,branch_location_id string,lob string, org_unit string, fa_num string, fa_split string)  stored as textfile')

DataFrame[result: string]

In [21]:
#Creating security dim. external textfile storage table
ss.sql('create external table if not exists usedcase.dim_security_ext(sec_id string,cusip string,start_dt string,end_dt string, symbl string, symbl_type string, quantity int, unit_price int)  stored as textfile')

DataFrame[result: string]

In [22]:
#Creating trade dim. external textfile storage table
ss.sql('create external table if not exists usedcase.dim_trade_ext(tarde_id int,trade_name string,trade_type string,trade_dt string, trade_settlement_dt string, transaction_type string, trade_quantity int)  stored as textfile')

DataFrame[result: string]

In [24]:
# Loading account dimensions temporary external table (always load incremental into the delta and add that to the dimensions(external))
ss.sql('drop table if exists usedcase.dim_acct_delta')
ss.sql('create table if not exists usedcase.dim_acct_delta as select * from usedcase.dim_acct_ext where 1=0')
ss.sql('insert into table usedcase.dim_acct_delta  select cast(land_trade_feed.acct_num as int),max(land_trade_feed.acct_name), \
max(land_trade_feed.acct_type), max(land_trade_feed.acct_sub_type) from \
usedcase.land_trade_feed land_trade_feed \
left outer join usedcase.dim_acct_ext dim_acct_ext \
on dim_acct_ext.acct_num =cast(land_trade_feed.acct_num as int)\
where dim_acct_ext.acct_num is null and  land_trade_feed.rec_id is not null group by land_trade_feed.acct_num')
ss.sql('insert into table usedcase.dim_acct_ext select * from usedcase.dim_acct_delta')

DataFrame[]

In [25]:
# Loading product dimensions temporary external table (always load incremental into the delta and add that to the dimensions(external))
ss.sql('drop table if exists usedcase.dim_product_delta ')
ss.sql('create table if not exists usedcase.dim_product_delta as select * from usedcase.dim_product_ext where 1=0')
ss.sql('insert into  table  usedcase.dim_product_delta select max(land_trade_feed.product_id),land_trade_feed.product_name, max(land_trade_feed.product_desc),max(land_trade_feed.product_category) from usedcase.land_trade_feed land_trade_feed left outer join usedcase.dim_product_ext dim_product_ext on dim_product_ext.product_name=land_trade_feed.product_name where dim_product_ext.product_name is null and land_trade_feed.rec_id is not null group by land_trade_feed.product_name')
ss.sql('insert into table usedcase.dim_product_ext select * from usedcase.dim_product_delta')

DataFrame[]

In [26]:
# Loading branch dimensions temporary external table (always load incremental into the delta and add that to the dimensions(external))
ss.sql('drop table if exists usedcase.dim_branch_delta ')
ss.sql('create table usedcase.dim_branch_delta as select * from usedcase.dim_branch_ext where 1=0')
ss.sql('insert into table usedcase.dim_branch_delta  \
select max(land_trade_feed.rec_id),land_trade_feed.branch_name, \
max(land_trade_feed.branch_location_id),max(land_trade_feed.lob), \
max(land_trade_feed.org_unit),max(land_trade_feed.fa_num),max(land_trade_feed.fa_split) \
from usedcase.land_trade_feed land_trade_feed \
left outer join usedcase.dim_branch_ext dim_branch_ext \
on dim_branch_ext.branch_name=land_trade_feed.branch_name \
where dim_branch_ext.branch_name is null  and land_trade_feed.rec_id is not null \
group by land_trade_feed.branch_name')
ss.sql('insert into table usedcase.dim_branch_ext select * from usedcase.dim_branch_delta')

DataFrame[]

In [27]:
# Loading security master dimensions temporary external table (always load incremental into the delta and add that to the dimensions(external))
ss.sql('drop table if exists usedcase.dim_security_delta ')
ss.sql('create table usedcase.dim_security_delta as select * from usedcase.dim_security_ext where 1=0')
ss.sql('insert into table usedcase.dim_security_delta select concat(land_trade_feed.cusip,substr(land_trade_feed.start_dt,3,2),substr(land_trade_feed.start_dt,6,2),substr(land_trade_feed.start_dt,9,2)),land_trade_feed.cusip, land_trade_feed.start_dt,max(land_trade_feed.end_dt),max(land_trade_feed.symbols),max(land_trade_feed.symbol_type), sum(land_trade_feed.quantity),sum(land_trade_feed.quantity) from usedcase.land_trade_feed land_trade_feed left outer join usedcase.dim_security_ext dim_security_ext on (dim_security_ext.cusip=land_trade_feed.cusip and dim_security_ext.start_dt=land_trade_feed.start_dt) where land_trade_feed.rec_id is not null and dim_security_ext.cusip is null group by land_trade_feed.cusip,land_trade_feed.start_dt')
ss.sql('insert into table usedcase.dim_security_ext select * from usedcase.dim_security_delta')

DataFrame[]

In [29]:
# Loading trade  dimensions temporary external table(always load incremental into the delta and add that to the dimensions(external))
ss.sql('drop table if exists usedcase.dim_trade_delta ')
ss.sql('create table usedcase.dim_trade_delta as select * from usedcase.dim_trade_ext where 1=0')
ss.sql('insert into usedcase.dim_trade_delta \
select land_trade_feed.trade_id,land_trade_feed.trade_name, \
land_trade_feed.trade_type, \
land_trade_feed.trade_dt,land_trade_feed.trade_settlement_dt, \
land_trade_feed.transaction_type,land_trade_feed.trade_quantity \
from usedcase.land_trade_feed land_trade_feed \
left outer join usedcase.dim_trade_ext dim_trade_ext \
on land_trade_feed.trade_id=dim_trade_ext.tarde_id \
where dim_trade_ext.tarde_id is null and land_trade_feed.rec_id is not null')
ss.sql('insert into table usedcase.dim_trade_ext select * from usedcase.dim_trade_delta')

DataFrame[]

In [31]:
# Create all managed table for the dimensions (stored as ORC)
ss.sql('create table if not exists  usedcase.dim_product(product_id int,product_name string,product_desc string,product_category string)  stored as orc')
ss.sql('create  table if not exists usedcase.dim_acct(acct_num int,acct_name string,acct_type string,acct_sub_type string)  stored as orc')
ss.sql('create  table if not exists usedcase.dim_branch(branch_id int,branch_name string,branch_location_id string,lob string, org_unit string, fa_num string, fa_split string)  stored as orc')
ss.sql('create  table if not exists usedcase.dim_security(sec_id string,cusip string,start_dt string,end_dt string, symbl string, symbl_type string, quantity int, unit_price int)  stored as orc')
ss.sql('create  table if not exists usedcase.dim_trade(tarde_id int,trade_name string,trade_type string,trade_dt string, trade_settlement_dt string, transaction_type string, trade_quantity int)  stored as orc')

DataFrame[result: string]

In [32]:
#Populate these tables with the data from the external tables (respective to each ORC there is a source external table)
ss.sql('insert overwrite table  usedcase.dim_product select *  from usedcase.dim_product_ext')
ss.sql('insert overwrite table  usedcase.dim_acct select *  from usedcase.dim_acct_ext')
ss.sql('insert overwrite table  usedcase.dim_branch select *  from usedcase.dim_branch_ext')
ss.sql('with temp as (select oq.sec_id,oq.cusip,oq.start_dt,min(sq.start_dt) min_start_dt,oq.end_dt,max(oq.symbl) symbl,max(oq.symbl_type) symbl_type,max(oq.quantity) quantity,max(oq.unit_price) unit_price from usedcase.dim_security_ext oq inner join  usedcase.dim_security_ext sq on oq.cusip=sq.cusip where to_date(oq.start_dt) <= to_date(sq.start_dt) group by oq.sec_id,oq.cusip,oq.start_dt, oq.end_dt) insert overwrite table  usedcase.dim_security select sec_id,cusip,start_dt,CASE WHEN start_dt = min_start_dt then end_dt else min_start_dt end,symbl,symbl_type,quantity,unit_price from temp')
ss.sql('insert overwrite table  usedcase.dim_trade select *  from usedcase.dim_trade_ext')

DataFrame[]

In [33]:
#Define and create a fact table for trade txn details
#( this is a factless fact marrying all the dimensions to capture their many:many relationship)
ss.sql('create table if not exists usedcase.fact_trade_txn_details (branch_id int, acct_num int,sec_id string ,trade_id int,product_id int ) stored as orc')

DataFrame[result: string]

In [34]:
# This Cross reference table will be rebuilt for every run
#(This is a fact less fact table just hoding the relatioship between dimensions)
ss.sql('insert overwrite table usedcase.fact_trade_txn_details \
select distinct b.branch_id,a.acct_num, s.sec_id,t.tarde_id,p.product_id \
from usedcase.land_trade_feed src \
inner join usedcase.dim_product p on (src.product_name=p.product_name) \
inner join usedcase.dim_branch b on (src.branch_name=b.branch_name) \
inner join usedcase.dim_acct a on (src.acct_num=a.acct_num) \
inner join usedcase.dim_trade t on (src.trade_name=t.trade_name) \
inner join usedcase.dim_security s on (src.cusip=s.cusip and src.start_dt=s.start_dt)')

DataFrame[]

In [ ]:
# Semantic views for prod based and loc based tran counts 
ss.sql('create view if not exists usedcase.prod_based_tran_trend as \
select  temp.product_name,temp.transaction_type, count(distinct temp.tarde_id) tran_cnt \
from  (select p.product_name,t.transaction_type,t.tarde_id \
from \
usedcase.fact_trade_txn_details f \
inner join usedcase.dim_product p \
on (f.product_id=p.product_id) \
inner join usedcase.dim_trade t \
on (f.trade_id=t.tarde_id)) temp \
group by temp.product_name,temp.transaction_type')

ss.sql('create view usedcase.loc_based_tran_trend as \
select  temp.branch_location_id,temp.transaction_type, count(distinct temp.tarde_id) tran_cnt \
from  (select b.branch_location_id,t.transaction_type,t.tarde_id \
from \
usedcase.fact_trade_txn_details f \
inner join usedcase.dim_branch b \
on (f.branch_id=b.branch_id) \
inner join usedcase.dim_trade t \
on (f.trade_id=t.tarde_id)) temp \
group by temp.branch_location_id,temp.transaction_type')